k
K
ka-li
kaki
kali
kali nitrat
kalium
kalium nitrat
kangaroo
kappa
karaoke
karate
kb
KB
KCS
ke
kè
kè kè
kè nhè
kẻ
kẻ ăn người làm
kẻ ăn người ở
kẻ ăn ốc người đổ vỏ
kẻ bắc người nam
kẻ cả
kẻ cắp
kẻ cắp gặp bà già
kẻ chợ
kẻ cướp
kẻ gian
kẻ ít người nhiều
kẻ ở người đi
kẻ sĩ
kẻ tám lạng người nủa cân
kẻ thù
kẻ trộm
kẻ tung người hứng
kẽ
ké
ké đầu ngựa
ké né
kẹ
kéc
kelvin
kem
kem cốc
kem cân
kem cây
kem kí
kem ký
kem que
kèm
kèm cặp
kèm nhà kèm nhèm
kèm nhèm
kẻm nhẻm kèm nhèm
kẽm
kém
kém cạnh
kém cỏi
kém hèn
ken
ken két
ken-vin
kèn
kèn bầu
kèn bóp
kèn co
kèn cor
kèn cựa
kèn hát
kèn kẹt
kèn trống
kén
kén cá chọn canh
kén chọn
kẻng
kenvin
keo
keo bẩn
keo cú
keo kiết
keo kiệt
keo sơn
keo tai tượng
keo tơ
keo xỉn
keo xương
kèo
kèo nài
kèo nèo
kèo nhèo
kẻo
kẻo mà
kẻo nữa
kẻo rồi
kẽo cà kẽo kẹt
kẽo kẹt
kéo
kéo bè kéo cánh
kéo bè kết đảng
kéo bộ
kéo cày trả nợ
kéo co
kéo dài
kéo gỗ
kéo lại
kéo theo
kẹo
kẹo cao su
kẹo đắng
kép
kép hát
kẹp
két
kẹt
keyboard
kê
kê biên
kê khai
kê kích
kê môn
kê úm
kề
kề cà
kề cận
kề miệng lỗ
kề vai sát cánh
kể
kể cả
kể hạnh
kể lể
kể ra
kế
kế cận
kế chân
kế hoạch
kế hoạch hoá
kế hoạch hoá gia đình
kế mẫu
kế nghiệp
kế nhiệm
kế phụ
kế sách
kế tập
kế thất
kế thừa
kế tiếp
kế toán
kế toán trưởng
kế tục
kế tự
kế vị
kệ
kệ nệ
kê-pi
kệ thây
kệ xác
kếch
kếch sù
kếch xù
kệch
kệch cỡm
kệch cợm
kềm
kềm chế
kên
kên kên
kền
kền kền
kênh
kênh kiệu
kênh rạch
kênh truyền hình
kênh xáng
kềnh
kềnh càng
kềnh kệch
kễnh
kệnh
kếp
kêpi
kết
kết án
kết bạn
kết cấu
kết cấu đất
kết cấu hạ tầng
kết chạ
kết cỏ ngậm vành
kết cuộc
kết dính
kết duyên
kết duyên Châu Trần
kết duyên Tấn Trần
kết dư
kết đoàn
kết đọng
kết giao
kết hôn
kết hợp
kết liên
kết liễu
kết luận
kết mạc
kết nạp
kết nghĩa
kết nguyền
kết nối
kết quả
kết thân
kết thúc
kết tinh
kết toán
kết tóc
kết tóc xe tơ
kết tội
kết tụ
kết tủa
kết từ
kết ước
kêu
kêu ca
kêu gào
kêu cầu
kêu gọi
kêu la
kêu nài
kêu rêu
kêu trời
kêu van
kều
kg
kha khá
khà
khả ái
khả biến
khả chuyển
khả dĩ
khả dụng
khả kiến
khả kính
khả năng
khả nghi
khả ố
khả quan
khả thi
khả thủ
khá
khá khẩm
khá giả
khác
khác biệt
khác gì
khác máu tanh lòng
khác nào
khác thể
khác thường
khạc
khách
khách khí
khách khứa
khách qua đường
khách quan
khách quan chủ nghĩa
khách sạn
khách sáo
khách thể
khách tình
khách vãng lai
khai
khai báo
khai bút
khai căn
khai chiến
khai cơ lập nghiệp
khai cuộc
khai diễn
khai đao
khai đề
khai giảng
khai hạ
khai hấn
khai hậu
khai hoa
khai hoa kết quả
khai hoả
khai hhoang
khai hội
khai khẩn
khai khoáng
khai mạc
khai mào
khai phá
khai phóng
khai phương
khai quang
khai quật
khai quốc
khai quốc công thần
khai sáng
khai sanh
khai sinh
khai sơn phá thạch
khai tâm
khai thác
khai thiên lập địa
khai thông
khai triển
khai trừ
khai trương
khai trường
khai tử
khai vị
khải ca
khải hoàn
khải hoàn ca
khái
khái huyết
khái luận
khái lược
khái niệm
khái quát
khái quát hoá
khái tính
kham
kham khổ
khảm
khám
khám đường
khám nghiệm
khám xét
khan
khan hiếm
khàn
khàn khàn
khản
khản đặc
khán
khán đài
khán giả
khán hộ
khán phòng
khán thính giả
khán thủ
khang cường
khang khác
khang kháng
khang kiện
khang ninh
khang trang
khang khái
khang tảng
kháng
kháng án
kháng cáo
kháng chiến
kháng cự
kháng nghị
kháng nguyên
kháng sinh
kháng thể
kháng viêm
khạng nạng
khanh
khanh khách
khanh tướng
khành khạch
khảnh
khánh
khánh chúc
khánh hạ
khánh kiệt
khánh tận
khánh thành
khánh tiết
khao
khao khao
khao khát
khao quân
khao thưởng
khao vọng
khào khào
khảo
khảo chứng
khảo cổ
khảo cổ học
khảo cứu
khảo dị
khảo đính
khảo hạch
khảo luận
khảo nghiệm
khảo quan
khảo sát
khảo thí
khảo thích
khảo tra
kháo
kháp
khạp
khát
khát khao
khát máu
khát vọng
khau
khau kháu
kháu
kháu khỉnh
khay
khảy
kháy
khắc
khác bạc
khắc cốt ghi tâm
khắc cốt ghi xương
khắc ghi
khắc hoạ
khắc khoải
khắc khổ
khắc kỉ
khắc kỷ
khắc lậu canh tàn
khắc nghiệt
khắc phục
khắc tinh
khặc khặc
khặc khè
khặc khừ
khăm
khăm khẳm
khăm khắm
khẳm
khắm
khắm lằm lặm
khắm lặm
khăn
khăn áo
khăn ăn
khăn đầu rìu
khăn đóng
khăn gói
khăn gói gió đưa
khăn gói quả mướp
khăn khẳn
khăn khắn
khăn mỏ quạ
khăn piêu
khăn quàng
khăn quàng đỏ
khăn san
khăn vuông
khăn xếp
khẳn
khắn
khắn khắn
khắn khít
khăng
khăng khăng
khăng khít
khằng
khằng khặc
khẳng định
khẳng khái
khẳng kheo
khẳng khiu
khắng khít
khắp
khắp chợ cùng quê
khắt khe
khấc
khâm liêm
khâm mạng
khâm mệnh
khâm sai
khâm sứ
khâm thiên giám
khấm khá
khẩn
khẩn cấp
khẩn cầu
khẩn hoang
khẩn khoản
khẩn nài
khẩn thiết
khẩn trương
khẩn yếu
khấn
khấn khứa
khấn vái
khấp kha khấp khểnh
khấp khểnh
khấp khởi
khập khà khập khiễng
khập khễnh
khập khiễng
khất
khất kha khất khưởng
khất khưởng
khất lần
khất sĩ
khất thực
khật khà khật khừ
khật khà khật khưỡng
khật khừ
khật khưỡng
khâu
khâu vá
khâu vắt
khẩu
khẩu chiến
khẩu cung
khẩu độ
khẩu độ tỉ đối
khẩu đội
khẩu đội trưởng
khẩu hiệu
khẩu khí
khẩu lệnh
khẩu ngữ
khẩu phần
khẩu Phật tâm xã
khẩu thiệt vô bằng
khẩu trang
khẩu vị
khấu
khấu đầu
khấu đầu khấu đuôi
khấu đuôi
khấu hao
khấu trừ
khấu trừ hao mòn
khe
khe khắt
khe khẽ
khe khé
khẻ
khẽ
khẽ khàng
khẽ khọt
khé
khẹc
khem
khem khổ
khen
khen khét
khen lao
khen ngợi
khen phò mã tốt áo
khen tặng
khen thưởng
khèn
khén
kheo
kheo khéo
kheo khư
khéo
khéo léo
khéo miệng
khéo mồm
khéo mồm khéo miệng
khéo tay
khép
khép kín
khép nép
khét
khét lèn lẹt
khét lẹt
khét tiếng
khê
khê đọng
khề khà
khế
khế cơm
khế ước
khệ nệ
khênh
khềnh
khểnh
khệnh khạng
khệnh khoạng
khêu
khêu giục
khêu gợi
khều
khi
khi dể
khi hồi
khi không
khi mạn
khi quân
khỉ
khỉ dạng người
khỉ độc
khỉ đột
khỉ gió
khỉ ho cò gáy
khí
khí áp
khí áp kế
khí các-bo-nic
khí cacbonic
khí carbonic
khí cầu
khí chất
khí công
khí cốt
khí cụ
khí cục
khí động học
khí đốt
khí gió
khí giới
khí hậu
khí hậu học
khí hiếm
khí huyết
khí hư
khí kém
khí khái
khí lực
khí nhạc
khí nổ
khí phách
khí quan
khí quản
khí quyển
khí sắc
khí sinh
khí số
khí tài
khí thải
khí than
khí thế
khí thiên nhiên
khí tiết
khí tĩnh học
khí trơ
khí tượng
khí tượng học
khí tượng nông nghiệp
khí tượng thuỷ văn
khí vị
khía
khía cạnh
khịa
khích
khích bác
khích động
khích lệ
khích nộ
khiêm
khiêm cung
khiêm nhường
khiêm nhượng
khiêm tốn
khiêm xưng
khiếm diện
khiếm khuyết
khiếm nhã
khiếm thị
khiếm thính
khiếm thực
khiên
khiên chế
khiên cưỡng
khiền
khiển
khiển trách
khiến
khiêng
khiêng vác
khiễng
khiếp
khiếp đảm
khiếp đởm
khiếp nhược
khiếp sợ
khiếp vía
khiếp vía kinh hồn
khiêu chiến
khiêu dâm
khiêu hấn
khiêu khích
khiêu vũ
khiếu
khiếu kiện
khiếu nại
khiếu oan
khiếu tố
khin khít
khìn khịt
khinh
khinh bạc
khinh bỉ
khinh binh
khinh chiến
khinh dể
khinh khi
khinh khí
khinh khí cầu
khinh khích
khinh khỉnh
khinh kị binh
khinh kỵ binh
khinh mạn
khinh miệt
khinh nhờn
khinh quân
khinh suất
khinh thị
khinh thường
khít
khít khao
khít khìn khịt
khít khịt
khít rịt
khịt
khíu
kho
kho bạc
kho bãi
kho quỹ
kho tàng
kho tàu
kho tộ
khò khè
khỏ
khó
khó ăn khó nói
khó chịu
khó coi
khó dễ
khó đăm đăm
khó gặm
khó khăn
khó lòng
khó người dễ ta
khó người khó ta
khó nhọc
khó ở
khó tính
khó tính khó nết
khoa
khoa bảng
khoa chân múa tay
khoa cử
khoa danh
khoa giáo
khoa giáp
khoa hoạn
khoa học
khoa học cơ bản
khoa học kĩ thuật
khoa học kỹ thuật
khoa học nhân văn
khoa học quân sự
khoa học tự nhiên
khoa học ứng dụng
khoa học viễn tưởng
khoa học xã hội
khoa mục
khoa ngoại
khoa nội
khoa trương
khoa trường
khoả
khoả lấp
khoả thân
khoả tử
khoá
khoá kéo
khoá luận
khoá sinh
khoá sổ
khoá trình
khoác
khoác áo
khoác lác
khoai
khoai dong
khoai đao
khoai khoái
khoai lang
khoai mài
khoai mì
khoai môn
khoai mỡ
khoai mùa
khoai nưa
khoai nước
khoai riềng
khoai sọ
khoai tây
khoai tía
khoai trụng
khoai từ
khoai vạc
khoái
khoái cảm
khoái cảm thẩm mĩ
khoái cảm thẩm mỹ
khoái chá
khoái chí
khoái hoạt
khoái khẩu
khoái lạc
khoái trá
khoan
khoan dung
khoan đãi
khoan hậu
khoan hoà
khoan hồng
khoan khoái
khoan nhượng
khoan thai
khoan thứ
khoản
khoản đãi
khoán
khoán sản
khoán trắng
khoán ước
khoang
khoang nhạc
khoảng
khoảng âm
khoảng cách
khoảng khoát
khoảng không
khoáng
khoáng chất
khoáng dật
khoáng đãng
khoáng đạt
khoáng sản
khoáng sàng
khoáng sàng học
khoáng thạch
khoáng thể
khoáng vật
khoáng vật học
khoanh
khoanh tay
khoanh tay chịu chết
khoanh tay rủ áo
khoảnh
khoảnh khắc
khoát
khoát đạt
khoáy
khoăm
khoằm
khoằm khoặm
khoặm
khoắng
khóc
khóc dạ đề
khóc dở mếu dở
khóc đứng khóc ngồi
khóc lóc
khóc than
khoe
khoe khoang
khoe mẽ
khoẻ
khoẻ khoắn
khoẻ mạnh
khoẻ re
khoé
khoé hạnh
khoen
khoeo
khoèo
khoét
khoi
khỏi
khỏi phải nói
khỏi vòng cong đuôi
khói
khói hương
khói sương
khom
khom khom
khom lưng uốn gối
khòm
khòm khòm
khóm
khọm
khòng khòng
khọt khẹt
khô
khô cằn
khô cứng
khô dầu
khô dầu là
khô đét
khô hạn
khô hanh
khô héo
khô khan
khô khát
khô khẳng
khô khốc
khô không khốc
khô kiệt
khô lạnh
khô mộc
khô rang
khô ráo
khô róc
khô vằn
khổ
khổ ải
khổ chiến
khổ chủ
khổ công
khổ cực
khổ dịch
khổ đau
khổ độc
khổ hải
khổ hạnh
khổ hình
khổ học
khổ luyện
khổ một nỗi
khổ não
khổ nhục
khổ nhục kế
khổ qua
khổ sai
khổ sâm
khổ sâm nam
khổ sở
khổ tâm
khổ tận cam lai
khổ thân
khố
khố dây
khố đỏ
khố lục
khố rách
khố rách áo ôm
khố tải
khố vàng
khố xanh
khố son bòn khố nâu
khốc hại
khốc liệt
khôi
khôi hài
khôi khoa
khôi ngô
khôi nguyên
khôi phục
khôi vĩ
khối
khối lượng
khối phố
khôn
khôn ba năm dại một giờ
khôn cùng
khôn hồn
khôn khéo
khôn lẽ
khôn lỏi
khôn lớn
khôn lường
khôn ngoan
khôn nguôi
khôn nhà dại chợ
khôn thiêng
khôn xiết
khốn
khốn cùng
khốn đốn
khốn khó
khốn khổ
khốn kiếp
khốn một nỗi
khốn nạn
khốn quẫn
không
không ăn được thì đạp đổ
không báo
không biết chừng
không bờ bến
không bù
không cánh mà bay
không chiến
không chừng
không có lửa sao có khói
không có lửa làm sao có khói
không dưng
không đâu
không đâu vào đâu
không đầu không đũa
không đội trời chung
không hẹn mà nên
không ít thì nhiều
không kèn không trống
không khéo
không khí
không kích
không lẽ
không lực
không lưu
không mấy khi
không môn
không một tấc đất cắm dùi
không nhiều thì ít
không những
không nói không rằng
không phận
không quân
không tài gì
không tài nào
không tặc
không thầy đố mày làm nên
không thể
không tiền khoáng hậu
không trách
không trung
không tưởng
không ưa hì dưa có dòi
không vận
Khổng giáo
khổng lồ
khổng tước
khống
khống chế
khống chỉ
khơ khớ
khờ dại
khờ khạo
khớ
khơi
khơi gợi
khơi khơi
khơi mào
khởi
khởi binh
khởi chiến
khởi công
khởi đầu
khởi điểm
khởi động
khởi hành
khởi hấn
khởi kiện
khởi loạn
khởi nghĩa
khởi nghiệp
khởi nguồn
khởi nguyên
khởi phát
khởi sắc
khởi sự
khởi thảo
khởi thuỷ
khởi tố
khởi tranh
khởi tử
khởi xướng
khới
khớp
khu
khu biệt
khu chế xuất
khu đệm
khu đội
khu phi quân sự
khu phố
khu tập thể
khu trù mật
khu trú
khu trục
khu trục hạm
khu tự trị
khu uỷ
khu vực
khu xử
khù khì
khù khờ
khú
khua
khua chân múa tay
khua chiêng gõ mõ
khua chiêng gióng trống
khua chuông gõ mõ
khua khoắng
khua môi múa mép
khuân
khuân vác
khuẩn
khuất
khuất bóng
khuất khúc
khuất nẻo
khuất núi
khuất phục
khuất tất
khuây
khuây khoả
khuấy
khuấy đảo
khuấy động
khuấy rối
khúc
khúc chiết
khúc côn cầu
khúc khích
khúc khuỷu
khúc mắc
khúc nhôi
khúc nôi
khúc xạ
khục
khuê các
khuê phòng
khuếch đại
khuếch khoác
khuếch tán
khuếch trương
khui
khum
khum khum
khúm na khúm núm
khúm núm
khung
khung cảnh
khung cửi
khung giá
khung hình phạt
khung thành
khùng
khùng khùng
khùng khục
khủng bố
khủng bố trắng
khủng hoảng
khủng hoảng chính trị
khủng hoảng kinh tế
khủng khiếp
khủng khỉnh
khủng long
khúng khắng
khụng khiệng
khuôn
khuôn dạng
khuôn hình
khuôn khổ
khuôn mặt
khuôn mẫu
khuôn nhạc
khuôn phép
khuôn sáo
khuôn thiêng
khuôn thức
khuôn vàng thước ngọc
khuôn viên
khuôn xanh
khuông
khuơ
khụt khịt
khuy
khuy bấm
khuy tết
khuỵ
khuya
khuya khoắt
khuya sớm
khuyên
khuyên bảo
khuyên can
khuyên dỗ
khuyên giải
khuyên giáo
khuyên lơn
khuyên nhủ
khuyên răn
khuyển
khuyển mã
khuyển ưng
khuyến cáo
khuyến dụ
khuyến học
khuyến khích
khuyến lâm
khuyến mãi
khuyến nghị
khuyến ngư
khuyến nông
khuyến tài
khuyến thiện
khuyết
khuyết danh
khuyết điểm
khuyết hám
khuyết tật
khuyết thiếu
khuynh
khuynh diệp
khuynh đảo
khuynh gia bại sản
khuynh hướng
khuynh loát
khuynh quốc khuynh thành
khuynh thành
khuỳnh
khuỳnh tay ngai
khuỷnh
khuýp
khuỷu
khuỵu
khư khư
khừ khừ
khử
khử trùng
khứ hồi
khứ lai
khứa
khứng
khựng
khước
khước từ
khươi
khướt
khượt
khướu
khứu giác
ki
ki bo
ki cóp
ki-lô
ki-mô-nô
ki-na-crin
ki ốt
kì
kì ảo
kì bí
kì binh
kì cạch
kì cọ
kì công
kì cục
kì cùng
kì cựu
kì dị
kì diệu
kì đà
kì đài
kì giồng
kì hào
kì hoa dị thảo
kì kèo
kì khôi
kì khu
kì lạ
kì lão
kì lân
kì mục
kì ngộ
kì nhông
kì phiếu
kì phùng địch thủ
kì quái
kì quan
kì quặc
kì tài
kì tập
kì thật
kì thị
kì thủ
kì thú
kì thuỷ
kì thực
kì tích
kì tình
kì trân
kì vĩ
kì vọng
kì yên
kỉ
kỉ cương
kỉ hà học
kỉ luật
kỉ lục
kỉ nguyên
kỉ niệm
kỉ vật
kỉ yếu
kĩ
kĩ càng
kĩ lưỡng
kĩ năng
kĩ nghệ
kĩ nghệ gia
kĩ nữ
kĩ sư
kĩ thuật
kĩ thuật số
kĩ thuật viên
kĩ tính
kĩ xảo
kí
kí âm
kí âm pháp
kí cả hai tay
kí chủ
kí cóp
kí cược
kí giả
kí giam
kí gửi
kí hiệu
kí hiệu học
kí hoạ
kí kết
kí lô
kí lục
kí ninh
kí quĩ
kí quỹ
kí sinh
kí sinh trùng
kí sự
kí tắt
kí tên
kí thác
kí túc
kí túc xá
kí tự
kí ức
kí vãng
kị
kị binh
kị binh bay
kị binh thiết giáp
kị khí
kị mã
kị nước
kị rơ
kị sĩ
kia
kia mà
kìa
kích
kích cầu
kích cỡ
kích dục
kích động
kích giá
kích hoạt
kích phát
kích tấc
kích thích
kích thích tố
kích thước
kích tố
kích ứng
kịch
kịch bản
kịch bản phim
kịch câm
kịch chiến
kịch chủng
kịch cọt
kịch cợm
kịch cương
kịch gia
kịch hát
kịch liệt
kịch mục
kịch ngắn
kịch nghệ
kịch nhạc
kịch nói
kịch phát
kịch sĩ
kịch tác gia
kịch thơ
kịch tính
kịch trường
kiêm
kiêm ái
kiêm nhiệm
kiêm tính
kiêm toàn
kiềm
kiềm chế
kiềm thúc
kiềm tính
kiềm toả
kiểm
kiểm chứng
kiểm dịch
kiểm duyệt
kiểm đếm
kiểm điểm
kiểm định
kiểm hoá
kiểm học
kiểm kê
kiểm lâm
kiểm ngân
kiểm nghiệm
kiểm ngư
kiểm nhận
kiểm phẩm
kiểm sát
kiểm sát viên
kiểm soát
kiểm thảo
kiểm thử
kiểm toán
kiểm toán viên
kiểm tra
kiểm tu
kiếm
kiếm ăn
kiếm chác
kiếm chuyện
kiếm củi ba năm thiêu một giờ
kiếm cung
kiếm hiệp
kiếm khách
kiếm thuật
kiệm
kiệm lời
kiệm ước
kiên cố
kiên cường
kiên dũng
kiên định
kiên gan
kiên nghị
kiên nhẫn
kiên quyết
kiên tâm
kiên trì
kiên trinh
kiên trung
kiền
kiền khôn
kiền kiền
kiến
kiến bò miệng chén
kiến càng
kiến cánh
kiến cỏ
kiến đen
kiến giả nhất phận
kiến giải
kiến giảng
kiến gió
kiến hiệu
kiến lập
kiến lửa
kiến nghị
kiến quốc
kiến tạo
kiến tạo học
kiến tập
kiến thiết
kiến tha lâu cũng đầy tổ
kiến thiết cơ bản
kiến thức
kiến trúc
kiến trúc đá
kiến trúc địa chất
kiến trúc sư
kiến trúc thượng tầng
kiến vàng
kiến văn
kiến vống
kiện
kiện cáo
kiện khang
kiện toàn
kiện tụng
kiện tướng
kiêng
kiêng cữ
kiêng dè
kiêng khem
kiêng kị
kiêng kỵ
kiêng nể
kiêng sợ
kiềng
kiểng
kiễng chân
kiễng gót
kiếng
kiếng mát
kiếp
kiết
kiết lị
kiết lỵ
kiết xác
kiệt
kiệt cùng
kiệt hiệt
kiệt lực
kiệt quệ
kiệt sức
kiệt tác
kiệt xuất
kiêu
kiêu bạc
kiêu binh
kiêu căng
kiêu dũng
kiêu hãnh
kiêu hùng
kiêu kì
kiêu kỳ
kiêu ngạo
kiêu sa
kiêu xa
kiều
kiều bào
kiều cư
kiều dân
kiều diễm
kiều hối
kiểu
kiểu cách
kiểu dáng
kiểu mẫu
kiểu sức
kiếu
kiếu từ
kiệu
kilo-
kilobit
kilobyte
kilogam
kilogram
kilomet
kilooat
kilooat-giờ
kilowatt
kilowatt-giờ
kim
kim anh
kim anh tử
kim bản vị
kim băng
kim cải
kim chỉ nam
kim cổ
kim cúc
kim cương
kim đan
kim đồng
kim đơn
kim giao
kim hoả
kim hoàn
kim khánh
kim khí
kim lan
kim loại
kim loại đen
kim loại hiếm
kim loại học
kim loại kiềm
kim loại màu
kim loại nguyên sinh
kim loại quý
kim loại sạch
kim loại tái sinh
kim loại thô
kim móc
kim môn
kim nam châm
kim ngạch
kim ngân
kim nhũ
kim ô
kim phượng
kim sinh học
kim thanh
kim thuộc
kim tiền
Kim Tinh
kim tuyến
kim tự tháp
kim tương học
kìm
kìm cộng lực
kìm giữ
kìm hãm
kìm kẹp
kìm nén
kimono
kimônô
kin kít
kìn kìn
kìn kịt
kín
kín cổng cao tường
kín đáo
kín mít
kín nhẽ
kín nhiệm
kín như bưng
kín tiếng
kinacrin
kin
kinh bang tế thế
kinh bổn
kinh cung chi điểu
kinh dị
kinh dinh
kinh doanh
kinh điển
kinh đô
kinh độ
kinh độ đông
kinh độ tây
kinh động
kinh giới
kinh hãi
kinh hoàng
kinh hoảng
kinh hồn
kinh hồn bạt vía
kinh hồn táng đởm
kinh kệ
kinh khủng
kinh kì
kinh kịch
kinh kỳ
kinh lạc
kinh lí
kinh lịch
kinh luận
kinh lược
kinh lược sứ
kinh lý
kinh ngạc
kinh nghĩa
kinh nghiệm
kinh nguyệt
kinh niên
kinh phí
kinh phong
kinh qua
kinh quyền
kinh rợn
kinh sợ
kinh sư
kinh sử
kinh tài
kinh tế
kinh tế hàng hoá
kinh tế học
kinh tế phụ gia đình
kinh tế thị trường
kinh tế tri thức
kinh tế tự nhiên
kinh thành
kinh Thánh
kinh thiên động địa
kinh tiêu
kinh tởm
kinh trập
kinh truyện
kinh tuyến
kinh tuyến gốc
kinh viện
kinh xáng
kình
kình địch
kình ngạc
kình nghê
kình ngư
kính
kính ảnh
kính cẩn
kính cận
kính dưỡng mục
kính đổi màu
kính hiển vi
kính hiển vi điện tử
kính lão
kính lão đắc thọ
kính lúp
kính mát
kính mến
kính nể
kính nhi viễn chi
kính phục
kính râm
kính thiên văn
kính thuốc
kính tiềm vọng
kính trọng
kính vạn hoa
kính viễn
kính viễn vọng
kính yêu
kíp
kiép chầy
kíp vi sai
kịp
kịp thời
kịt
Kitô giáo
kĩu cà kĩu kịt
kĩu kịt
km
KT
KTT
kW
kW-h
kỳ
kỳ ảo
kỳ bí
kỳ binh
kỳ công
kỳ cục
kỳ cùng
kỳ cựu
kỳ dị
kỳ diệu
kỳ đà
kỳ đài
kỳ giông
kỳ hạn
kỳ hào
kỳ hoa dị thảo
kỳ khôi
kỳ khu
kỳ lạ
kỳ lão
kỳ lân
kỳ mục
kỳ ngộ
kỳ nhông
kỳ phiếu
kỳ phùng địch thủ
kỳ quái
kỳ quan
kỳ quặc
kỳ tài
kỳ tập
kỳ thật
kỳ thị
kỳ thủ
kỳ thú
kỳ thuỷ
kỳ thực
kỳ tích
kỳ tình
kỳ trân
kỳ vĩ
kỳ vọng
kỳ yên
kỷ
kỷ cương
kỷ hà học
kỷ luật
kỷ nguyên
kỷ niệm
kỷ vật
kỷ yếu
kỹ
kỹ càng
kỹ lưỡng
kỹ năng
kỹ nghệ
kỹ nghệ gia
kỹ nữ
kỹ sư
kỹ thuật
kỹ thuật số
kỹ thuật viên
kỹ tính
kỹ xảo
ký
ký âm
ký âm pháp
ký cả hai tay
ký chủ
ký cược
ký giả
ký giam
ký gửi
ký hiệu
ký hiệu học
ký hoạ
ký kết
ký lô
ký lục
ký quỹ
ký sinh
ký sinh trùng
ký sự
ký tắt
ký tên
ký thác
ký túc
ký túc xá
ký tự
ký ức
ký vãng
kỵ
kỵ binh
kỵ binh bay
kỵ binh thiết giáp
kỵ khí
kỵ mã
kỵ nước
kỵ rơ
kỵ sĩ
